-- Table that stores the reports generated by the system
CREATE TABLE report (
    id SERIAL PRIMARY KEY, -- Unique identifier of the report
    file_name TEXT NOT NULL, -- Name of the processed file
    date TIMESTAMP NOT NULL, -- Date and time of file processing
    isProcessed BOOLEAN NOT NULL, -- Indicates whether the file has been processed or not
    total FLOAT, -- Total of the file movements
    avrDebit FLOAT, -- Average of the file debit movements
    avrCredit FLOAT, -- Average of the file credit movements
    send_to TEXT[], -- Emails to which the report should be sent
    error TEXT, -- Error message if the file cannot be processed
    CONSTRAINT unique_file_date UNIQUE (file_name, date) -- Restriction to prevent duplicate records
);

-- Table that stores the number of transactions per month
CREATE TABLE transactions_by_month (
    id SERIAL PRIMARY KEY, -- Unique identifier of the record
    month INTEGER NOT NULL, -- Month number
    num_transactions INTEGER NOT NULL, -- Number of transactions recorded in the month
    report_id INTEGER NOT NULL, -- Identifier of the report to which the record belongs
    CONSTRAINT unique_tr_by_month UNIQUE (report_id, month), -- Restriction to prevent duplicate records
    CONSTRAINT fk_report_id FOREIGN KEY (report_id) REFERENCES report(id) -- Foreign key that references the "report" table
);

-- Table that stores the details of the transactions
CREATE TABLE transactions (
    id SERIAL PRIMARY KEY, -- Unique identifier of the record
    report_id INTEGER REFERENCES report(id), -- Identifier of the report to which the transaction belongs
    number INTEGER NOT NULL, -- Transaction number
    date DATE NOT NULL, -- Transaction date
    movement VARCHAR(20) NOT NULL, -- Type of movement (debit or credit)
    value FLOAT NOT NULL -- Transaction value
);

-- Table that stores the transactions ignored by the system
CREATE TABLE ignored_transactions (
    id SERIAL PRIMARY KEY, -- Unique identifier of the record
    report_id INTEGER REFERENCES report(id), -- Identifier of the report to which the ignored transaction belongs
    ignored_id TEXT NOT NULL, -- Unique identifier of the ignored transaction
    date TEXT NOT NULL, -- Date of the ignored transaction
    transaction TEXT NOT NULL, -- Description of the ignored transaction
    reason TEXT NOT NULL -- Reason why the transaction was ignored
);
